# Generated by Django 3.1.7 on 2021-03-11 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribuicao', models.CharField(choices=[('exe', 'Executante'), ('resp', 'Responsável')], max_length=100)),
                ('aptidao', models.BooleanField()),
                ('ASO', models.BooleanField()),
                ('entrega_prevista', models.DateTimeField()),
                ('abertura_OS', models.DateTimeField()),
                ('finalizacao_OS', models.DateTimeField(blank=True, null=True)),
                ('HT', models.FloatField(default=0)),
                ('QTD', models.IntegerField(default=0)),
                ('adicional', models.FloatField(default=0)),
                ('HE', models.FloatField(default=0)),
                ('HE_percentual', models.FloatField(default=0)),
                ('AN', models.FloatField(default=0)),
                ('deslocamento_quilometragem', models.FloatField(default=0)),
                ('pedagio', models.FloatField(default=0)),
                ('outros', models.FloatField(default=0)),
                ('custo', models.FloatField(default=0)),
                ('detalhamento', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente')),
                ('executante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executante_colaborador', to='cadastro.colaborador')),
                ('modalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modalidade_ordem', to='cadastro.modalidade')),
                ('modalidade_avulsa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modalidade_ordemavulsa', to='cadastro.modalidade')),
                ('qualificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.qualificacao')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_colaborador', to='cadastro.colaborador')),
                ('servicos', models.ManyToManyField(to='cadastro.Servico')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
            },
        ),
    ]
