# Generated by Django 3.1.7 on 2021-04-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_de_servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_de_custo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('prazo', models.IntegerField()),
                ('grupo', models.CharField(choices=[('E', 'Externo'), ('I', 'Interno')], max_length=100)),
                ('metodo_de_cobranca', models.CharField(choices=[('diaria', 'Diária'), ('horas', 'Horas'), ('quantidade', 'Quantidade'), ('adicional', 'Adicional'), ('md -50 / dc +50', 'MD -50% / DC +50%')], max_length=100)),
                ('qualificacao', models.CharField(max_length=100)),
                ('atribuicao', models.CharField(choices=[('exe', 'Executante'), ('resp', 'Responsável')], max_length=100)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.RemoveField(
            model_name='ordem',
            name='servicos',
        ),
    ]
