# Generated by Django 3.1.7 on 2021-04-06 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_auto_20210331_1106'),
        ('ordem_de_servico', '0002_auto_20210405_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={},
        ),
        migrations.CreateModel(
            name='ServicoAdicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_servico', models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True)),
                ('Valor_deslocamento', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordem_de_servico.ordem')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.servico')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
