# Generated by Django 2.0.13 on 2021-05-09 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_de_servico', '0004_auto_20210509_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='AN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposta_AN', to='proposta.Proposta'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='HE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposta_HE', to='proposta.Proposta'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='HE_percentual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposta_HE_percentual', to='proposta.Proposta'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='HT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposta_HT', to='proposta.Proposta'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposta_custo', to='proposta.Proposta'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='deslocamento_quilometragem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposta_deslocamento', to='proposta.Proposta'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='pedagio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposta_pedagio', to='proposta.Proposta'),
        ),
    ]
