# Generated by Django 3.1.7 on 2021-03-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprasTeceiros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidocompra', models.CharField(blank=True, choices=[('env', 'Enviado'), ('emit', 'Emitido'), ('nemit', 'Não Emitido')], max_length=100, null=True)),
                ('pagamentocompra', models.CharField(blank=True, choices=[('pg', 'Pago'), ('npg', 'Não Pago')], max_length=100, null=True)),
                ('pcnumero', models.CharField(blank=True, max_length=100, null=True)),
                ('pcitem', models.CharField(blank=True, max_length=100, null=True)),
                ('notafiscal', models.CharField(blank=True, max_length=200, null=True)),
                ('ht', models.FloatField(blank=True, null=True)),
                ('qtd', models.FloatField(blank=True, null=True)),
                ('he', models.FloatField(blank=True, null=True)),
                ('he_percent', models.CharField(blank=True, choices=[('50', '50%'), ('75', '75%'), ('100', '100%')], max_length=100, null=True)),
                ('an', models.FloatField(blank=True, null=True)),
                ('desloc_km', models.FloatField(blank=True, null=True)),
                ('pedagio', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('despesa', 'Despesa'), ('servico', 'Serviço')], max_length=150, null=True)),
                ('custo', models.FloatField(blank=True, null=True)),
                ('servicos', models.ManyToManyField(to='cadastro.Servico')),
            ],
            options={
                'verbose_name': 'Compra de Terceirizada',
                'verbose_name_plural': 'Compras de Terceiros',
            },
        ),
    ]
