# Generated by Django 3.1.7 on 2021-03-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20210312_0712'),
        ('compras_terceiros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprasteceiros',
            old_name='an',
            new_name='anormalidade',
        ),
        migrations.RenameField(
            model_name='comprasteceiros',
            old_name='he',
            new_name='horas_extras',
        ),
        migrations.RenameField(
            model_name='comprasteceiros',
            old_name='he_percent',
            new_name='horas_extras_percentuais',
        ),
        migrations.RenameField(
            model_name='comprasteceiros',
            old_name='ht',
            new_name='horas_trabalhadas',
        ),
        migrations.RenameField(
            model_name='comprasteceiros',
            old_name='pagamentocompra',
            new_name='pagamento_compra',
        ),
        migrations.RenameField(
            model_name='comprasteceiros',
            old_name='pcitem',
            new_name='pc_item',
        ),
        migrations.RenameField(
            model_name='comprasteceiros',
            old_name='pcnumero',
            new_name='pc_numero',
        ),
        migrations.RenameField(
            model_name='comprasteceiros',
            old_name='pedidocompra',
            new_name='pedido_compra',
        ),
        migrations.AddField(
            model_name='comprasteceiros',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprasteceiros',
            name='inspetor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.colaborador'),
        ),
        migrations.AddField(
            model_name='comprasteceiros',
            name='numero_os',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comprasteceiros',
            name='projeto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ItemCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('compras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras_terceiros.comprasteceiros')),
            ],
        ),
    ]
