# Generated by Django 3.1.7 on 2021-03-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras_terceiros', '0002_auto_20210312_0731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcompras',
            options={'verbose_name': 'Item da Compra', 'verbose_name_plural': 'Itens da Compra'},
        ),
    ]
