# Generated by Django 3.1.7 on 2021-04-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_terceiros', '0005_comprasteceiros_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasteceiros',
            name='condicao_de_pagamento',
            field=models.CharField(blank=True, choices=[('28ddl', '28ddl'), ('45ddl', '45ddl'), ('variavel', 'Variável')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comprasteceiros',
            name='metodo_de_pagamento',
            field=models.CharField(blank=True, choices=[('boleto', 'Boleto'), ('transferencia', 'Transferência Bancária')], max_length=100, null=True),
        ),
    ]
