# Generated by Django 3.1.7 on 2021-04-06 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_auto_20210331_1106'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendas',
            options={},
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='servicos',
        ),
        migrations.CreateModel(
            name='ServicoVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_servico', models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True)),
                ('Valor_deslocamento', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.vendas')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.servico')),
            ],
            options={
                'verbose_name': 'Venda ',
                'verbose_name_plural': 'Vendas ',
            },
        ),
    ]
