# Generated by Django 3.1.7 on 2021-04-11 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20210406_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='PV_IT',
        ),
    ]
