# Generated by Django 3.1.7 on 2021-04-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_remove_vendas_pv_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='vendedor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
