# Generated by Django 3.1.7 on 2021-04-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_vendas_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicovenda',
            name='OS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
