# Generated by Django 3.1.7 on 2021-04-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_servicovenda_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicovenda',
            name='OS',
        ),
        migrations.AddField(
            model_name='vendas',
            name='OS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
