# Generated by Django 3.1.7 on 2021-04-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_auto_20210413_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='AN',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='HE',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='HE_percentual',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='HT',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='QTD',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='adicional',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='descricao_venda',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='filtro_desloc',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='filtro_serv',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='preco_servico',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='preco_venda',
        ),
        migrations.AddField(
            model_name='servicovenda',
            name='AN',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='servicovenda',
            name='HE',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='servicovenda',
            name='HE_percentual',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='servicovenda',
            name='HT',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='servicovenda',
            name='QTD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicovenda',
            name='adicional',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='servicovenda',
            name='descricao_venda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicovenda',
            name='filtro_desloc',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='servicovenda',
            name='filtro_serv',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='servicovenda',
            name='preco_servico',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='servicovenda',
            name='preco_venda',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
