# Generated by Django 3.1.7 on 2021-03-11 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contato', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=30, null=True)),
                ('rua', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('kras', 'Kras'), ('terceiro', 'Terceiro')], max_length=100)),
                ('metodo_cobranca', models.CharField(blank=True, choices=[('diaria', 'Diária'), ('horas', 'Horas')], max_length=100, null=True)),
                ('valor_diaria', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('valor_hora', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('valor_km', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('custo_ASO', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('custo_NRs', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('custo_pedagio', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('custo_hospedagem', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('cursto_in_tinere', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('endereço', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('agencia', models.CharField(blank=True, max_length=100, null=True)),
                ('conta', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.IntegerField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('cnh', models.CharField(blank=True, max_length=50, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('boleto', 'Boleto'), ('debito_conta', 'Débito')], max_length=100, null=True)),
                ('valor_contrato', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('dia_pagamento', models.IntegerField(blank=True, null=True)),
                ('condicao_pagamento', models.CharField(blank=True, choices=[('apos-relatorio', 'Após a entrega de relatório'), ('apos-finalizacao', 'Após a finalização do projeto')], max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centrocusto', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao_compras', models.CharField(blank=True, max_length=100, null=True)),
                ('unidade', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contato', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=30, null=True)),
                ('rua', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_custo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('metodo_de_cobranca', models.CharField(choices=[('diaria', 'Diária'), ('horas', 'Horas'), ('quantidade', 'Quantidade'), ('adicional', 'Adicional'), ('md -50 / dc +50', 'MD -50% / DC +50%')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qualificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.IntegerField()),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Qualificação',
                'verbose_name_plural': 'Qualificações',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_de_custo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('prazo', models.IntegerField()),
                ('grupo', models.CharField(choices=[('E', 'Externo'), ('I', 'Interno')], max_length=100)),
                ('metodo_de_cobranca', models.CharField(choices=[('diaria', 'Diária'), ('horas', 'Horas'), ('quantidade', 'Quantidade'), ('adicional', 'Adicional'), ('md -50 / dc +50', 'MD -50% / DC +50%')], max_length=100)),
                ('qualificacao', models.CharField(max_length=100)),
                ('atribuicao', models.CharField(choices=[('exe', 'Executante'), ('resp', 'Responsável')], max_length=100)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='ColaboradorDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='documento_colaborador')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='AtribuicaoDeQualificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validade', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.colaborador')),
                ('qualificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.qualificacao')),
            ],
            options={
                'verbose_name': 'Qualificação do Colaborador',
                'verbose_name_plural': 'Qualificações do Colaborador',
            },
        ),
    ]
