# Generated by Django 3.1.7 on 2021-03-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='cursto_in_tinere',
            new_name='custo_in_tinere',
        ),
        migrations.AddField(
            model_name='atribuicaodequalificacao',
            name='valor_contratado',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atribuicaodequalificacao',
            name='valor_de_qualificacao',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=6),
            preserve_default=False,
        ),
    ]
