# Generated by Django 3.1.7 on 2021-03-11 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20210311_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamesASO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExamesNR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ColaboradorNR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.colaborador')),
                ('tipo_do_exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.examesnr')),
            ],
        ),
        migrations.CreateModel(
            name='ColaboradorASO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.colaborador')),
                ('tipo_do_exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.examesaso')),
            ],
        ),
    ]
