# Generated by Django 3.1.7 on 2021-03-11 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_colaboradoraso_colaboradornr_examesaso_examesnr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='custo_ASO',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='custo_NRs',
        ),
    ]
