# Generated by Django 3.1.7 on 2021-03-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20210312_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atribuicaodequalificacao',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='atribuicaodequalificacao',
            name='valor_contratado',
        ),
        migrations.RemoveField(
            model_name='atribuicaodequalificacao',
            name='valor_de_qualificacao',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='cnh',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='custo_hospedagem',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='validade',
        ),
        migrations.RemoveField(
            model_name='colaboradoraso',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='colaboradornr',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='centrocusto',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='qualificacao',
            name='id_item',
        ),
        migrations.AddField(
            model_name='atribuicaodequalificacao',
            name='valor_de_requalificacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atribuicaodequalificacao',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='CNH',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='banco_codigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='banco_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='horario_in_tinere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='validade_CNH',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaboradoraso',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaboradoraso',
            name='valor_atualizacao',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='colaboradoraso',
            name='valor_exame',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='colaboradornr',
            name='acessorios',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='colaboradornr',
            name='valor_atualizacao',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='colaboradornr',
            name='valor_exame',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='centro_custo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='custo_pedagio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
