# Generated by Django 3.1.7 on 2021-03-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_auto_20210323_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='centro_custo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compras',
            name='codigo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='contato',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
