# Generated by Django 3.1.7 on 2021-04-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_auto_20210331_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
