# Generated by Django 3.1.7 on 2021-03-31 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_clienteservico'),
        ('proposta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='AN',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proposta',
            name='ASO',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='HE',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proposta',
            name='HE_percentual',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proposta',
            name='HT',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proposta',
            name='QTD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposta',
            name='abertura_OS',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='adicional',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proposta',
            name='aptidao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='atribuicao',
            field=models.CharField(blank=True, choices=[('exe', 'Executante'), ('resp', 'Responsável')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='custo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proposta',
            name='deslocamento_quilometragem',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proposta',
            name='detalhamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='entrega_prevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='executante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposta_executante', to='cadastro.colaborador'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='finalizacao_OS',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='modalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposta_ordem', to='cadastro.modalidade'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='modalidade_avulsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposta_ordemavulsa', to='cadastro.modalidade'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='outros',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proposta',
            name='pedagio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proposta',
            name='qualificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.qualificacao'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposta_responsavel', to='cadastro.colaborador'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='servicos',
            field=models.ManyToManyField(to='cadastro.Servico'),
        ),
    ]
