# Generated by Django 3.1.7 on 2021-04-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0003_auto_20210406_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='servicos',
        ),
    ]
