# Generated by Django 2.0.13 on 2021-04-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0004_remove_proposta_servicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='ASO',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='aptidao',
            field=models.NullBooleanField(),
        ),
    ]
