# Generated by Django 2.0.13 on 2021-05-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0005_auto_20210423_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='QTD',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='abertura_OS',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='entrega_prevista',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='executante',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='finalizacao_OS',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='modalidade',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='modalidade_avulsa',
        ),
        migrations.AddField(
            model_name='servicoproposta',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicoproposta',
            name='qtd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicoproposta',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
