# Generated by Django 2.0.13 on 2021-05-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0006_auto_20210504_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicoproposta',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
