# Generated by Django 2.0.13 on 2021-05-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0007_auto_20210504_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposta',
            options={'verbose_name': 'Proposta', 'verbose_name_plural': 'Propostas'},
        ),
    ]
