# Generated by Django 3.1.7 on 2021-03-11 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PG', models.CharField(blank=True, max_length=100, null=True)),
                ('PG_IT', models.CharField(blank=True, max_length=100, null=True)),
                ('Data', models.DateField(blank=True, null=True)),
                ('unidade', models.CharField(blank=True, max_length=50, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('status_ps', models.CharField(blank=True, choices=[('enviado', 'Enviado'), ('emitido', 'Emitido'), ('naoemitido', 'Não Emitido')], max_length=100, null=True)),
                ('pagamento', models.CharField(blank=True, choices=[('pago', 'Pago'), ('naopago', 'Não Pago')], max_length=100, null=True)),
                ('notafiscal', models.CharField(blank=True, max_length=150, null=True)),
                ('detalhamento', models.CharField(blank=True, max_length=200, null=True)),
                ('custo_pedido', models.DecimalField(blank=True, decimal_places=10, max_digits=50, null=True)),
                ('cod_fornec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.fornecedor')),
                ('descricao', models.ManyToManyField(blank=True, null=True, to='cadastro.Compras')),
            ],
            options={
                'verbose_name': 'Compra ',
                'verbose_name_plural': 'Compras ',
            },
        ),
    ]
