# Generated by Django 3.1.7 on 2021-03-12 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_compras_valor_imposto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='custo_pedido',
        ),
    ]
