# Generated by Django 3.1.7 on 2021-03-12 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20210312_0712'),
        ('compras', '0006_remove_compras_custo_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='PG',
            new_name='PC',
        ),
        migrations.RenameField(
            model_name='compras',
            old_name='PG_IT',
            new_name='PC_IT',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='cod_fornec',
        ),
        migrations.AddField(
            model_name='compras',
            name='condicao_de_pagamento',
            field=models.CharField(blank=True, choices=[('28ddl', '28ddl'), ('45ddl', '45ddl'), ('variavel', 'Variável')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='forma_entrega',
            field=models.CharField(blank=True, choices=[('email', 'E-mail'), ('retira', 'Retira'), ('transportadora', 'Transportadora')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.fornecedor'),
        ),
        migrations.AddField(
            model_name='compras',
            name='frases_padrao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='metodo_de_cobranca',
            field=models.CharField(blank=True, choices=[('nf+nd', 'NF+ND'), ('nf', 'NF')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='metodo_de_pagamento',
            field=models.CharField(blank=True, choices=[('nf+nd', 'NF+ND'), ('nf', 'NF')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='status_pc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='tipo_de_progresso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
