# Generated by Django 3.1.7 on 2021-03-14 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20210312_0712'),
        ('compras', '0007_auto_20210312_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compras',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.RemoveField(
            model_name='compras',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='valor',
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(blank=True, max_length=50, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compras')),
                ('descricao', models.ManyToManyField(to='cadastro.Compras')),
            ],
            options={
                'verbose_name': 'Item da Compra',
                'verbose_name_plural': 'Itens da Compra',
            },
        ),
    ]
