# Generated by Django 3.1.7 on 2021-03-14 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20210312_0712'),
        ('compras', '0008_auto_20210314_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcompra',
            name='descricao',
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='descricao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.compras'),
        ),
    ]
