# Generated by Django 3.1.7 on 2021-03-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_auto_20210314_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='detalhamento',
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='detalhamento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
