# Generated by Django 3.1.7 on 2021-03-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_auto_20210314_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='metodo_de_pagamento',
            field=models.CharField(blank=True, choices=[('boleto', 'Boleto'), ('transferencia', 'Transferência Bancária')], max_length=100, null=True),
        ),
    ]
